tn_classifier.normalize()
tn_classifier.iso_towards(0, trunc = True)
tn_classifier.iso_towards(tn_classifier.num_sites-1, trunc = True)

entropy = tn_classifier.meas_bond_entropy()
entropy_l = entropy.values()
x_array = np.arange(len(entropy_l))
plt.bar(x_array, np.array(list(entropy_l)))
plt.ylabel('Von Neumann Entropy', fontsize = 14)
plt.xlabel('Feature Index', fontsize = 14)
